[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin=lib/openzeppelin-contracts', '@openzeppelin-upgrades=lib/openzeppelin-contracts-upgradeable/contracts', '@chainlink=lib/chainlink', '@uniswap=lib/uniswap']
# See more config options https://github.com/foundry-rs/foundry/tree/master/config