[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin=lib/openzeppelin-contracts', '@openzeppelin-upgrades=lib/openzeppelin-contracts-upgradeable/contracts', '@chainlink=lib/chainlink', '@uniswap=lib/uniswap']

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"